### ISSUE TITLE
巴拉了一天，找到你了。

### ISSUE THREAD

**Issue by LuoooB** [niudaii/go-find#1]
找这个工具找了一天了。终于找到个满意的了。
提个小建议，
做的体积再小一电，然后支持自定义字符串。

**Comment by niudaii** [comment]
> 找这个工具找了一天了。终于找到个满意的了。 提个小建议， 做的体积再小一电，然后支持自定义字符串。

体积可以编译完用upx压缩哦，还有你说的自定义字符串是指肾摸呀

**Comment by apsry** [comment]
> > 找这个工具找了一天了。终于找到个满意的了。 提个小建议， 做的体积再小一电，然后支持自定义字符串。
> 
> 体积可以编译完用upx压缩哦，还有你说的自定义字符串是指肾摸呀

应该是指自定义关键词吧，确实有这个需求

**Comment by niudaii** [comment]
> > > 找这个工具找了一天了。终于找到个满意的了。 提个小建议， 做的体积再小一电，然后支持自定义字符串。
> > 
> > 
> > 体积可以编译完用upx压缩哦，还有你说的自定义字符串是指肾摸呀
> 
> 应该是指自定义关键词吧，确实有这个需求
使用参数 -k, --keywords string          keywords, split by comma
